package com.example.demo.controller;

import com.example.demo.entity.CurrentUser;
import com.example.demo.entity.Reservation;
import com.example.demo.entity.Workspace;
import com.example.demo.service.ReservationService;
import com.example.demo.service.WorkspaceService;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.scene.control.*;

import java.time.LocalDateTime;
import java.time.format.DateTimeParseException;
import java.util.List;

public class ReservationController {

    @FXML
    private ComboBox<String> workspaceComboBox;

    @FXML
    private TextField startTimeField;

    @FXML
    private TextField endTimeField;

    @FXML
    private ComboBox<String> statusField;

    @FXML
    private Button submitButton;

    @FXML
    private Label statusLabel;

    private final ReservationService reservationService = new ReservationService();
    private final WorkspaceService workspaceService = new WorkspaceService();

    private List<Workspace> workspaces; // Store the list of workspaces
    // Store the ID of the logged-in user

    // Method to set the logged-in user ID (called during controller initialization)

    @FXML
    public void initialize() {
        // Fetch all workspaces from the database
        workspaces = workspaceService.getAllWorkspaces();

        // Populate ComboBox with workspace names
        ObservableList<String> workspaceNames = FXCollections.observableArrayList(
                workspaces.stream()
                        .map(Workspace::getName)  // Extract the name property of each workspace
                        .toList()
        );

        // Set items in the ComboBox
        workspaceComboBox.setItems(workspaceNames);

        ObservableList<String> statusNames = FXCollections.observableArrayList(
                "pending"

        );
        statusField.setItems(statusNames);

    }

    @FXML
    private void handleSubmitAction() {
        try {
            CurrentUser currentUser = CurrentUser.getInstance();
            int userId = currentUser.getId();

            // Get values from fields
            String workspaceName = workspaceComboBox.getValue();
            String startTimeText = startTimeField.getText();
            String endTimeText = endTimeField.getText();
            String status = statusField.getValue();

            // Validate workspace selection
            if (workspaceName == null || workspaceName.trim().isEmpty()) {
                statusLabel.setText("Error: Please select a workspace.");
                return;
            }

            // Find the workspace ID based on the selected name
            int workspaceId = getWorkspaceIdFromName(workspaceName);

            // Validate and parse start and end times
            LocalDateTime startTime = parseDateTime(startTimeText);
            LocalDateTime endTime = parseDateTime(endTimeText);

            if (endTime.isBefore(startTime)) {
                statusLabel.setText("Error: End time must be after start time.");
                return;
            }

            // Validate status
            if (status == null || status.trim().isEmpty()) {
                statusLabel.setText("Error: Status cannot be empty.");
                return;
            }

            // Create a Reservation object (ID is auto-generated by the database)
            Reservation reservation = new Reservation(0, startTime,endTime, userId,workspaceId, status);

            // Call service to add reservation
            reservationService.addReservation(reservation);


            statusLabel.setText("Reservation added successfully!");
            statusField.cancelEdit();
            startTimeField.clear();
            endTimeField.clear();
            workspaceComboBox.cancelEdit();

        } catch (DateTimeParseException e) {
            statusLabel.setText("Error: Invalid date/time format. Use yyyy-MM-ddTHH:mm.");
        } catch (Exception e) {
            statusLabel.setText("Error: Failed to add reservation.");
            e.printStackTrace();
        }
    }

    private LocalDateTime parseDateTime(String dateTimeText) {
        return LocalDateTime.parse(dateTimeText);
    }

    private int getWorkspaceIdFromName(String workspaceName) {
        // Search for the selected workspace by name in the list of workspaces
        for (Workspace workspace : workspaces) {
            if (workspace.getName().equals(workspaceName)) {
                return workspace.getId();
            }
        }
        throw new IllegalArgumentException("Workspace not found: " + workspaceName);
    }
}
